'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {FakeModel}=require('./helpers/phase79FakeModels');
const sp=require.resolve(path.join(__dirname,'..','src/services/searchService.js'));const prev=require.cache[sp];require.cache[sp]={id:sp,filename:sp,loaded:true,exports:{async searchStaffs(){return[];}}};
const debt=require('../src/services/v2/debtNew.service');const ar=require('../src/services/arLedgerRead.service');const posting=require('../src/services/arPosting.service');const event=require('../src/services/accounting/CloseoutCorrectionArEventDeltaPostingService');
function makeOrder(code){return{id:`SO-${code}`,orderId:`SO-${code}`,salesOrderId:`SO-${code}`,code,orderCode:code,salesOrderCode:code,customerCode:`C-${code}`,customerName:'Boundary',accountingConfirmed:true,accountingStatus:'confirmed'};}
function opening(o,amount){return{id:`OPEN-${o.code}`,code:`OPEN-${o.code}`,account:'AR',category:'AR-DEBT-OPEN',ledgerType:'AR-DEBT-OPEN',entryType:'normal',type:'ar-debt-open',date:'2026-08-09',sourceType:'DELIVERY_CLOSEOUT',sourceId:o.id,sourceCode:o.code,refType:'DELIVERY_CLOSEOUT',refId:o.id,refCode:o.code,orderId:o.id,orderCode:o.code,salesOrderId:o.id,salesOrderCode:o.code,customerCode:o.customerCode,customerName:o.customerName,debit:amount,credit:0,amount,direction:'debit',amountField:'debit',status:'posted',active:true,reversed:false,deleted:false,isDeleted:false,accountingConfirmed:true,accountingStatus:'confirmed',createdAt:'2026-08-09T00:00:00Z',updatedAt:'2026-08-09T00:00:00Z'};}
async function scenario(raw){const o=makeOrder(`B-${raw}`), initial=1000000, rows=[opening(o,initial)], model=new FakeModel(rows), empty=new FakeModel([]);debt.setModelsForTest({ArLedger:model,DebtCollection:empty,OrderPaymentAllocation:empty});ar.setModelsForTest({ArLedger:model});posting.setModelsForTest({ArLedger:model,SalesOrder:{},AuditLog:{}});const cash=initial-raw;await event.postCorrectionEventDelta({order:o,correction:{id:`D-${raw}`,code:`D-${raw}`,correctionId:`D-${raw}`,correctionCode:`D-${raw}`,newCloseoutVersion:2,orderId:o.id,orderCode:o.code,salesOrderId:o.id,salesOrderCode:o.code,customerCode:o.customerCode,customerName:o.customerName,cashDeltaAmount:cash},version:{closeoutVersion:2}},{actor:'r1p2',now:'2026-08-09T01:00:00Z',zeroTolerance:1000});const grouped=debt.groupLedgers(rows,{status:'all'});const order=grouped.orders.find(x=>x.orderCode===o.code);return{order};}
test.afterEach(()=>{debt.setModelsForTest(null);ar.setModelsForTest(null);posting.setModelsForTest(null);});test.after(()=>{if(prev)require.cache[sp]=prev;else delete require.cache[sp];});
for(const [raw,expected] of [[0,0],[999,0],[1000,0],[1001,1001]]) test(`R1P2 DebtNew tolerance raw=${raw} => ${expected}`,async()=>{const {order}=await scenario(raw);assert.ok(order);assert.equal(order.debt,expected);assert.equal(order.debtAmount,expected);assert.equal(order.remainingDebt,expected);});
