const dataService = require('./dataService');
const { num, cleanCode } = require('../utils/coreUtils');

function asArray(v){ return Array.isArray(v) ? v : []; }
function esc(v){ return String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function money(v){ return num(v).toLocaleString('vi-VN'); }
function dateText(v){ return String(v || '').slice(0, 19).replace('T',' '); }
function inRange(date, from, to){ const d = String(date || '').slice(0,10); return (!from || d >= from) && (!to || d <= to); }
function css(){ return `
  <style>
  *{box-sizing:border-box} body{font-family:Arial,Helvetica,sans-serif;margin:16px;color:#111;font-size:12px} .page{max-width:1120px;margin:auto}
  .company{display:flex;justify-content:space-between;gap:16px}.company b{font-size:14px}.title{text-align:center;font-family:'Times New Roman',serif;font-size:22px;font-weight:700;margin:14px 0 6px;text-transform:uppercase}
  .sub{text-align:center;margin:0 0 12px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:6px 24px;margin:10px 0}.meta div{border-bottom:1px dotted #aaa;padding:3px 0}
  table{width:100%;border-collapse:collapse} th,td{border:1px solid #333;padding:4px 5px;vertical-align:top} th{background:#eee;text-align:center}.right{text-align:right}.center{text-align:center}.bold{font-weight:700}
  .section{margin-top:14px}.warehouse-title{background:#ddd;border:1px solid #333;padding:6px 8px;font-weight:700;margin-top:12px}.summary{display:flex;justify-content:flex-end;margin-top:8px}.summary table{width:420px}.sign{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;text-align:center;margin-top:28px}.sign div{min-height:70px}.muted{color:#666}.no-border td{border:0}.print-actions{position:sticky;top:0;background:#fff;padding:8px 0;margin-bottom:8px;border-bottom:1px solid #ddd}.btn{padding:7px 10px;border:1px solid #444;background:#f7f7f7;border-radius:6px;cursor:pointer}
  @media print{.print-actions{display:none} body{margin:0}.page{max-width:none}.warehouse-title{break-after:avoid} thead{display:table-header-group}}
  </style>`; }
function htmlShell(title, body){ return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>${esc(title)}</title>${css()}</head><body><div class="print-actions"><button class="btn" onclick="window.print()">In / Lưu PDF</button></div><div class="page">${body}</div></body></html>`; }
function companyBlock(){ return `<div class="company"><div><b>CÔNG TY / NPP MINH KHAI</b><br>Địa chỉ: Cầu Cánh Sẻ, Quang Bình, Thái Bình<br>ĐT/Fax: 0396198753</div><div class="right">Ngày in: ${esc(new Date().toLocaleString('vi-VN'))}</div></div>`; }
function productMap(db){ const m = new Map(); asArray(db.products).forEach(p => m.set(cleanCode(p.sku || p.productCode || p.code), p)); return m; }
function orderTotal(o){ return num(o.total || o.finalAmount || o.amount || asArray(o.items).reduce((s,it)=>s+num(it.qty||it.quantity)*num(it.sale||it.price),0)); }
function orderDebt(o){ return num(o.debt || o.debtAmount || Math.max(orderTotal(o)-num(o.paid||o.paidAmount),0)); }
function linesOf(o, db){ const pm = productMap(db); return asArray(o.items).map((it,idx)=>{ const p = pm.get(cleanCode(it.sku || it.productCode)) || {}; const qty=num(it.qty ?? it.quantity); const price=num(it.sale ?? it.price); const discount=num(it.discountAmount ?? it.discount); const amount=num(it.amount || qty*price-discount); return {idx:idx+1, sku:it.sku || it.productCode, name:it.name || it.productName || p.name || p.productName, unit:p.unit || it.unit || 'Cái', warehouse:p.warehouse || it.warehouseCode || o.warehouseCode || 'Kho chính', qty, price, discount, amount}; }); }
async function orderPrint(orderId){ const db = await dataService.getDb(); const id=cleanCode(orderId); const o=asArray(db.orders).find(x=>cleanCode(x.id || x.orderCode)===id); if(!o) throw new Error('Không tìm thấy đơn hàng'); const lines=linesOf(o, db); const totalQty=lines.reduce((s,x)=>s+x.qty,0); const total=orderTotal(o); const body=`${companyBlock()}<div class="title">Bảng kê đơn lẻ / Phiếu giao nhận và thanh toán</div><div class="sub">Chuyển đổi từ mẫu S3IM: BangKeHoaDon</div><div class="meta"><div><b>Số đơn:</b> ${esc(o.id || o.orderCode)}</div><div><b>Ngày:</b> ${esc(dateText(o.date || o.orderDate || o.createdAt))}</div><div><b>Khách hàng:</b> ${esc([o.customerCode,o.customerName].filter(Boolean).join(' - '))}</div><div><b>NVBH:</b> ${esc([o.staffCode||o.salesStaffCode,o.staffName||o.salesStaffName].filter(Boolean).join(' - '))}</div><div><b>NV giao:</b> ${esc([o.deliveryStaffCode,o.deliveryStaffName].filter(Boolean).join(' - '))}</div><div><b>Nguồn:</b> ${esc(o.source || '')}</div></div><table><thead><tr><th>STT</th><th>Mã hàng</th><th>Tên sản phẩm</th><th>ĐVT</th><th>Kho</th><th>SL</th><th>Đơn giá</th><th>CK</th><th>Thành tiền</th></tr></thead><tbody>${lines.map(x=>`<tr><td class="center">${x.idx}</td><td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td class="center">${esc(x.unit)}</td><td>${esc(x.warehouse)}</td><td class="right">${money(x.qty)}</td><td class="right">${money(x.price)}</td><td class="right">${money(x.discount)}</td><td class="right">${money(x.amount)}</td></tr>`).join('')}<tr><td colspan="5" class="right bold">Tổng cộng</td><td class="right bold">${money(totalQty)}</td><td colspan="2"></td><td class="right bold">${money(total)}</td></tr></tbody></table><div class="summary"><table><tr><td>Tổng tiền</td><td class="right bold">${money(total)}</td></tr><tr><td>Đã thu</td><td class="right">${money(o.paid || o.paidAmount)}</td></tr><tr><td>Còn nợ</td><td class="right bold">${money(orderDebt(o))}</td></tr></table></div><div class="sign"><div>Người lập biểu</div><div>Người bán hàng</div><div>Nhân viên giao hàng</div><div>Khách hàng</div></div>`; return htmlShell('Phiếu đơn hàng '+(o.id||''), body); }
function warehouseSummary(orders, db){ const map={}; orders.forEach(o=>linesOf(o, db).forEach(it=>{ const wh=it.warehouse || 'Kho chính'; map[wh]=map[wh]||{}; const key=cleanCode(it.sku); map[wh][key]=map[wh][key]||{sku:it.sku,name:it.name,unit:it.unit,qty:0,amount:0}; map[wh][key].qty+=it.qty; map[wh][key].amount+=it.amount; })); return Object.entries(map).map(([warehouse,items])=>({warehouse, items:Object.values(items)})); }
async function masterPrint(masterId){ const db=await dataService.getDb(); const id=cleanCode(masterId); const master=asArray(db.masterOrders).find(x=>cleanCode(x.id || x.masterCode || x.batchCode)===id); if(!master) throw new Error('Không tìm thấy đơn tổng'); const childIds=asArray(master.childIds).map(cleanCode); const orders=asArray(db.orders).filter(o=>cleanCode(o.masterId)===id || childIds.includes(cleanCode(o.id || o.orderCode))); const wh=warehouseSummary(orders, db); const totalValue=orders.reduce((s,o)=>s+orderTotal(o),0); const totalQty=wh.reduce((s,w)=>s+w.items.reduce((a,it)=>a+it.qty,0),0); const body=`${companyBlock()}<div class="title">Bảng kê đơn lẻ gộp / Phiếu bố hàng đơn tổng</div><div class="sub">Chuyển đổi từ mẫu S3IM: BangKeHoaDon-Lo-Giao-Nhan-Gop</div><div class="meta"><div><b>Mã đơn tổng:</b> ${esc(master.id || master.masterCode || master.batchCode)}</div><div><b>Ngày giờ xuất:</b> ${esc(dateText(master.exportTime || master.date))}</div><div><b>NV giao hàng:</b> ${esc([master.deliveryStaffCode,master.deliveryStaffName].filter(Boolean).join(' - '))}</div><div><b>Số đơn con:</b> ${orders.length}</div><div><b>Tổng SL:</b> ${money(totalQty)}</div><div><b>Tổng tiền:</b> ${money(totalValue)}</div></div>${wh.map(w=>`<div class="warehouse-title">Kho: ${esc(w.warehouse)}</div><table><thead><tr><th>STT</th><th>Mã hàng</th><th>Tên sản phẩm</th><th>ĐVT</th><th>SL lẻ</th><th>Giá trị</th><th>Ghi chú</th></tr></thead><tbody>${w.items.map((it,i)=>`<tr><td class="center">${i+1}</td><td>${esc(it.sku)}</td><td>${esc(it.name)}</td><td class="center">${esc(it.unit)}</td><td class="right bold">${money(it.qty)}</td><td class="right">${money(it.amount)}</td><td></td></tr>`).join('')}<tr><td colspan="4" class="right bold">Tổng kho ${esc(w.warehouse)}</td><td class="right bold">${money(w.items.reduce((s,it)=>s+it.qty,0))}</td><td class="right bold">${money(w.items.reduce((s,it)=>s+it.amount,0))}</td><td></td></tr></tbody></table>`).join('')}<div class="section"><b>Danh sách đơn con:</b> ${orders.map(o=>esc(o.id||o.orderCode)).join(', ')}</div><div class="sign"><div>Thủ kho</div><div>Người bố hàng</div><div>Nhân viên giao hàng</div><div>Kế toán</div></div>`; return htmlShell('Đơn tổng '+(master.id||''), body); }
async function salesReport(params={}){ const db=await dataService.getDb(); const from=params.fromDate||params.from||''; const to=params.toDate||params.to||''; const staff=cleanCode(params.staffCode||params.salesStaffCode||''); const rows=asArray(db.orders).filter(o=>inRange(o.date||o.orderDate||o.createdAt,from,to)).filter(o=>!staff || cleanCode(o.staffCode||o.salesStaffCode)===staff); const group={}; rows.forEach(o=>{ const day=String(o.date||o.orderDate||o.createdAt||'').slice(0,10); const st=[o.staffCode||o.salesStaffCode,o.staffName||o.salesStaffName].filter(Boolean).join(' - ') || 'Chưa có NV'; const key=day+'|'+st; group[key]=group[key]||{date:day,staff:st,orders:0,qty:0,total:0,debt:0}; group[key].orders+=1; group[key].qty+=asArray(o.items).reduce((s,it)=>s+num(it.qty||it.quantity),0); group[key].total+=orderTotal(o); group[key].debt+=orderDebt(o); }); const out=Object.values(group).sort((a,b)=>a.date.localeCompare(b.date)||a.staff.localeCompare(b.staff)); return {sourceTemplate:'BC-BH-NV-NGAY', params:{fromDate:from,toDate:to,staffCode:staff}, rows:out, totals:{orders:out.reduce((s,x)=>s+x.orders,0), qty:out.reduce((s,x)=>s+x.qty,0), total:out.reduce((s,x)=>s+x.total,0), debt:out.reduce((s,x)=>s+x.debt,0)}}; }
async function debtReport(params={}){ const db=await dataService.getDb(); const from=params.fromDate||params.from||''; const to=params.toDate||params.to||''; const rows=[]; const byCustomer={}; asArray(db.orders).filter(o=>inRange(o.date||o.orderDate||o.createdAt,from,to)).forEach(o=>{ const key=cleanCode(o.customerCode); byCustomer[key]=byCustomer[key]||{customerCode:o.customerCode,customerName:o.customerName,openingBalance:0,salesAmount:0,collectedAmount:0,adjustment:0,closingBalance:0}; byCustomer[key].salesAmount+=orderDebt(o); }); asArray(db.payments).filter(p=>inRange(p.date||p.createdAt,from,to)).forEach(p=>{ const key=cleanCode(p.customerCode); byCustomer[key]=byCustomer[key]||{customerCode:p.customerCode,customerName:p.customerName,openingBalance:0,salesAmount:0,collectedAmount:0,adjustment:0,closingBalance:0}; byCustomer[key].collectedAmount+=num(p.cash)+num(p.bank)+num(p.amount); }); asArray(db.debtLedger).forEach(l=>{ const key=cleanCode(l.customerCode); byCustomer[key]=byCustomer[key]||{customerCode:l.customerCode,customerName:l.customerName,openingBalance:num(l.openingBalance),salesAmount:0,collectedAmount:0,adjustment:num(l.adjustment),closingBalance:0}; byCustomer[key].openingBalance=num(l.openingBalance); byCustomer[key].adjustment=num(l.adjustment); }); Object.values(byCustomer).forEach(r=>{ r.closingBalance=num(r.openingBalance)+num(r.salesAmount)-num(r.collectedAmount)+num(r.adjustment); if(r.openingBalance||r.salesAmount||r.collectedAmount||r.adjustment||r.closingBalance) rows.push(r); }); rows.sort((a,b)=>String(a.customerName||a.customerCode).localeCompare(String(b.customerName||b.customerCode),'vi')); return {sourceTemplate:'BC-CN-KH-PhaiThu-Tuyen-Ngay', params:{fromDate:from,toDate:to}, rows, totals:{openingBalance:rows.reduce((s,x)=>s+x.openingBalance,0),salesAmount:rows.reduce((s,x)=>s+x.salesAmount,0),collectedAmount:rows.reduce((s,x)=>s+x.collectedAmount,0),adjustment:rows.reduce((s,x)=>s+x.adjustment,0),closingBalance:rows.reduce((s,x)=>s+x.closingBalance,0)}}; }
function reportHtml(title, report, columns){ const body=`${companyBlock()}<div class="title">${esc(title)}</div><div class="sub">Từ ${esc(report.params.fromDate||'...')} đến ${esc(report.params.toDate||'...')} · Mẫu S3IM: ${esc(report.sourceTemplate)}</div><table><thead><tr>${columns.map(c=>`<th>${esc(c.label)}</th>`).join('')}</tr></thead><tbody>${report.rows.map(r=>`<tr>${columns.map(c=>`<td class="${c.cls||''}">${c.format?c.format(r[c.key],r):esc(r[c.key])}</td>`).join('')}</tr>`).join('') || `<tr><td colspan="${columns.length}" class="center muted">Không có dữ liệu</td></tr>`}<tr>${columns.map((c,i)=>`<td class="${c.cls||''} bold">${i===0?'Tổng':(report.totals[c.key]!==undefined?money(report.totals[c.key]):'')}</td>`).join('')}</tr></tbody></table>`; return htmlShell(title, body); }
async function salesReportHtml(params){ const r=await salesReport(params); return reportHtml('Báo cáo bán hàng theo nhân viên / ngày', r, [{key:'date',label:'Ngày'},{key:'staff',label:'Nhân viên'},{key:'orders',label:'Số đơn',cls:'right',format:v=>money(v)},{key:'qty',label:'SL',cls:'right',format:v=>money(v)},{key:'total',label:'Doanh số',cls:'right',format:v=>money(v)},{key:'debt',label:'Còn nợ',cls:'right',format:v=>money(v)}]); }
async function debtReportHtml(params){ const r=await debtReport(params); return reportHtml('Báo cáo công nợ khách hàng phải thu', r, [{key:'customerCode',label:'Mã KH'},{key:'customerName',label:'Tên khách hàng'},{key:'openingBalance',label:'Nợ đầu',cls:'right',format:v=>money(v)},{key:'salesAmount',label:'Phát sinh',cls:'right',format:v=>money(v)},{key:'collectedAmount',label:'Đã thu',cls:'right',format:v=>money(v)},{key:'adjustment',label:'Điều chỉnh',cls:'right',format:v=>money(v)},{key:'closingBalance',label:'Nợ cuối',cls:'right',format:v=>money(v)}]); }
module.exports={ orderPrint, masterPrint, salesReport, debtReport, salesReportHtml, debtReportHtml };
