'use strict';

const READ_ENDPOINT_BUDGETS = Object.freeze({
  products: Object.freeze({
    screen: 'Sản phẩm',
    endpoint: 'GET /api/products',
    frontendFiles: Object.freeze(['public/js/app/02-products.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'short-session-catalog-only'
  }),
  customers: Object.freeze({
    screen: 'Khách hàng',
    endpoint: 'GET /api/customers',
    frontendFiles: Object.freeze(['public/js/app/03-customers-autocomplete.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'short-session-catalog-only'
  }),
  salesOrders: Object.freeze({
    screen: 'Bán hàng',
    endpoint: 'GET /api/sales-orders',
    frontendFiles: Object.freeze(['public/js/app/05-sales-orders.source/part-04.jsfrag', 'public/js/app/05-sales-orders.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'order-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-orders'
  }),
  masterOrders: Object.freeze({
    screen: 'Đơn tổng',
    endpoint: 'GET /api/master-orders',
    frontendFiles: Object.freeze(['public/js/app/06-master-delivery.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'master-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-orders'
  }),
  deliveryTodayOrders: Object.freeze({
    screen: 'Đơn giao hôm nay New',
    endpoint: 'GET /api/new/delivery-today/orders',
    frontendFiles: Object.freeze(['public/js/app/new/91-delivery-today-new.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: false,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 500,
    projection: 'orders-primary-delivery-today-list-summary-with-masterorders-metadata-only',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-closeout-state'
  }),
  debtNewCustomers: Object.freeze({
    screen: 'Công nợ New',
    endpoint: 'GET /api/new/debt/customers',
    frontendFiles: Object.freeze(['public/js/app/new/92-debt-new.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'debt-customer-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-debt'
  }),
  debtCollections: Object.freeze({
    screen: 'Thu nợ chờ xác nhận',
    endpoint: 'GET /api/debt-collections',
    frontendFiles: Object.freeze(['public/js/app/new/92-debt-new.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'collection-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-debt'
  }),
  returnOrders: Object.freeze({
    screen: 'Đơn trả hàng',
    endpoint: 'GET /api/return-orders',
    frontendFiles: Object.freeze(['public/js/app/debt/07b-return-orders.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'return-order-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-return-stock-state'
  }),
  fundsLedger: Object.freeze({
    screen: 'Quỹ tiền - Sổ quỹ',
    endpoint: 'GET /api/funds/ledger',
    frontendFiles: Object.freeze(['public/js/app/debt/07f-fund-ledger.source/part-01.jsfrag']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'fund-ledger-list-summary',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-fund'
  }),
  fundsSummary: Object.freeze({
    screen: 'Quỹ tiền - Tổng hợp',
    endpoint: 'GET /api/funds/summary',
    frontendFiles: Object.freeze(['public/js/app/debt/07f-fund-ledger.source/part-01.jsfrag']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'fund-summary-list',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-fund'
  }),
  reportCatalog: Object.freeze({
    screen: 'Báo cáo - Danh mục báo cáo',
    endpoint: 'GET /api/reports/catalog',
    frontendFiles: Object.freeze(['public/js/app/admin/08a-reports.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'report-catalog-definition-only',
    reloadPolicy: 'single-catalog-request',
    cachePolicy: 'session-catalog-cache'
  }),
  reports: Object.freeze({
    screen: 'Báo cáo',
    endpoint: 'GET /api/reports/*',
    frontendFiles: Object.freeze(['public/js/app/admin/08a-reports.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 500,
    projection: 'report-preview-page',
    reloadPolicy: 'one-active-report-request',
    cachePolicy: 'catalog-cache-only'
  }),
  dmsInventoryLatest: Object.freeze({
    screen: 'Đối chiếu DMS',
    endpoint: 'GET /api/dms-inventory/latest',
    frontendFiles: Object.freeze(['public/js/app/10-dms-inventory.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'dms-comparison-page',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-inventory'
  }),
  dmsInventoryHistory: Object.freeze({
    screen: 'Đối chiếu DMS - Lịch sử',
    endpoint: 'GET /api/dms-inventory/history',
    frontendFiles: Object.freeze(['public/js/app/10-dms-inventory.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'dms-history-list',
    reloadPolicy: 'lazy-load-history-tab',
    cachePolicy: 'short-session-history'
  }),
  dmsGapSimulatorPreview: Object.freeze({
    screen: 'Sinh đơn chấm DMS',
    endpoint: 'POST /api/tools/dms-gap-simulator/preview',
    frontendFiles: Object.freeze(['public/js/app/tools/dms-gap-simulator.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: false,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 500,
    projection: 'preview-only',
    reloadPolicy: 'command-like-preview-request',
    cachePolicy: 'none-for-inventory'
  }),
  displayCheck: Object.freeze({
    screen: 'Quản lý chấm Trưng bày',
    endpoint: 'GET /api/tools/display-check/*',
    frontendFiles: Object.freeze(['public/js/app/tools/display-check-manager.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 200,
    projection: 'display-check-list-summary',
    reloadPolicy: 'lazy-load-active-tab',
    cachePolicy: 'short-session-config-only'
  }),
  mobileCustomers: Object.freeze({
    screen: 'App bán hàng - Khách hàng',
    endpoint: 'GET /api/mobile/customers',
    frontendFiles: Object.freeze(['public/mobile/js/sales.source/part-01.jsfrag']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'mobile-customer-card',
    reloadPolicy: 'page-or-load-more-request',
    cachePolicy: 'short-session-catalog-only'
  }),
  mobileProducts: Object.freeze({
    screen: 'App bán hàng - Sản phẩm',
    endpoint: 'GET /api/mobile/products',
    frontendFiles: Object.freeze(['public/mobile/js/sales.source/part-02.jsfrag']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'mobile-product-card-with-stock',
    reloadPolicy: 'page-or-load-more-request',
    cachePolicy: 'short-session-product-search-only'
  }),
  mobileSalesOrders: Object.freeze({
    screen: 'App bán hàng - Đơn hàng',
    endpoint: 'GET /api/mobile/sales/orders',
    frontendFiles: Object.freeze(['public/mobile/js/sales.source/part-03.jsfrag']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 50,
    projection: 'mobile-order-card',
    reloadPolicy: 'page-or-load-more-request',
    cachePolicy: 'none-for-orders'
  }),
  mobileDebts: Object.freeze({
    screen: 'App bán hàng/giao hàng - Công nợ',
    endpoint: 'GET /api/mobile/debts',
    frontendFiles: Object.freeze(['public/mobile/js/delivery-mobile-view.source.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 50,
    projection: 'mobile-debt-customer-card',
    reloadPolicy: 'lazy-load-debt-tab-page',
    cachePolicy: 'none-for-debt'
  }),
  deliveryOrders: Object.freeze({
    screen: 'App giao hàng - Đơn giao',
    endpoint: 'GET /api/delivery/orders',
    frontendFiles: Object.freeze(['public/mobile/js/delivery-mobile-view.source.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'delivery-mobile-order-card',
    reloadPolicy: 'single-orders-request',
    cachePolicy: 'short-lived-order-list-only'
  }),
  deliveryReconciliation: Object.freeze({
    screen: 'App giao hàng - Đối soát',
    endpoint: 'GET /api/delivery/reconciliation',
    frontendFiles: Object.freeze(['public/mobile/js/delivery-mobile-view.source.js']),
    maxRequestsPerUserAction: 1,
    requiresPagination: false,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 1,
    projection: 'delivery-reconciliation-summary',
    reloadPolicy: 'lazy-load-reconciliation-tab',
    cachePolicy: 'none-for-financial-summary'
  }),
  warehouseReturnChecks: Object.freeze({
    screen: 'App thủ kho - Kiểm hàng trả',
    endpoint: 'GET /api/mobile/warehouse/return-checks',
    frontendFiles: Object.freeze(['public/mobile/warehouse-return-check.html']),
    maxRequestsPerUserAction: 1,
    requiresPagination: true,
    requiresAbortableFrontend: false,
    acceptsSequenceGuard: true,
    readOnly: true,
    forbiddenWrites: true,
    maxLimit: 100,
    projection: 'warehouse-return-check-list',
    reloadPolicy: 'single-list-request',
    cachePolicy: 'none-for-return-state'
  })
});

function getReadEndpointBudget(name) {
  return READ_ENDPOINT_BUDGETS[name] || null;
}

module.exports = {
  READ_ENDPOINT_BUDGETS,
  getReadEndpointBudget
};
