'use strict';

module.exports = Object.freeze({
  SALE_CONFIRMED: 'SALE_CONFIRMED',
  SALE_CANCELLED: 'SALE_CANCELLED',
  RETURN_CONFIRMED: 'RETURN_CONFIRMED',
  RETURN_CANCELLED: 'RETURN_CANCELLED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  MASTER_ORDER_ASSIGNED: 'MASTER_ORDER_ASSIGNED',
  DELIVERY_CONFIRMED: 'DELIVERY_CONFIRMED'
});
