/* GENERATED FILE — edit templates/printTemplates.source/part-01.jsfrag, templates/printTemplates.source/part-02.jsfrag, templates/printTemplates.source/part-03.jsfrag and run npm run build:source-bundles. */
const t=require("./print/dmsExactSalesInvoice.template");function n(t){
return String(t??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}function e(t,n){
return t.formatMoney?t.formatMoney(n):Number(n||0).toLocaleString("vi-VN")}function o(t,e=""){return n(t||e)}function s(t){return t.erpInvoiceV46||{}}function i(t){
const n=s(t).header||{};return{invoiceCode:n.invoiceCode||t.document?.invoiceCode||t.document?.code||"",orderCode:n.orderCode||t.document?.customerOrderCode||t.document?.code||"",
orderDateTime:n.orderDateTime||t.document?.dateTime||t.document?.date||"",invoiceType:n.invoiceType||t.document?.type||"Từ NVTT",
paymentTerm:n.paymentTerm||t.document?.terms||"đáo hạn trong 7 ngày",truckNo:n.truckNo||t.document?.vehicleNo||"",taxCode:n.taxCode||t.customer?.taxCode||""}}function r(t){
const n=s(t).distributor||{};return{code:n.code||t.company?.code||"3293",name:n.name||t.company?.name||"Công Ty TNHH MTV Minh Khai",phone:n.phone||t.company?.phone||"",
address:n.address||t.company?.address||""}}function a(t){const n=s(t).customer||{};return{customerCode:n.customerCode||t.customer?.code||"",
customerName:n.customerName||t.customer?.name||"",phone:n.phone||t.customer?.phone||"",deliveryAddress:n.deliveryAddress||t.customer?.address||"",
taxCode:n.taxCode||t.customer?.taxCode||""}}function d(t){const n=s(t).salesStaff||{};return{staffCode:n.staffCode||t.staff?.code||"",staffName:n.staffName||t.staff?.name||"",
phone:n.phone||t.staff?.phone||""}}function c(t){const n=s(t);return Array.isArray(n.items)&&n.items.length?n.items:(t.items||[]).map(t=>({...t,lineNo:t.lineNo||t.stt,
productCode:t.productCode||t.code,productName:t.productName||t.name,quantityCsSu:t.quantityCsSu||t.caseDisplay,quantity:t.quantity??t.qty,
priceBeforeTaxBeforePromotion:t.priceBeforeTaxBeforePromotion??t.listPriceBeforeVat??t.priceBeforeVat??t.price,
priceAfterTaxBeforePromotion:t.priceAfterTaxBeforePromotion??t.listPriceAfterVat??t.priceAfterVatBeforeDiscount,
priceAfterTaxAfterPromotion:t.priceAfterTaxAfterPromotion??t.priceAfterVatAfterDiscount??t.priceAfterDiscount,vatAmount:t.vatAmount??t.tax,lineAmount:t.lineAmount??t.amount,
isPromotionGift:t.isPromotionGift??t.isPromo,promotionRows:t.promotionRows||[],appliedPromotions:t.appliedPromotions||[],promotions:t.promotions||[],
productSnapshot:t.productSnapshot||{},product:t.product||{}}))}function l(t){return Array.isArray(t)?t:[]}function m(t){
return[...l(t?.promotionRows),...l(t?.appliedPromotions),...l(t?.promotions),...l(t?.productSnapshot?.promotions),...l(t?.product?.promotions)]}function u(t,n={}){
const e=t?.promotionCode||t?.code||t?.programCode||t?.ctkmCode||"",o=n.productCode||n.code||t?.productCode||"",s=n.productName||n.name||t?.productName||"",i=n.priceBeforeTaxBeforePromotion??n.beforeTaxAmount??n.amountBeforeTax??n.lineAmount??n.amount??0
;return{...t,promotionCode:e,code:e,description:t?.description||t?.promotionDescription||t?.programDescription||t?.promotionName||t?.name||t?.title||"",
qualifiedAmount:t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??t?.purchaseAmountBeforeTax??t?.purchaseAmount??t?.goodsAmountBeforeTax??t?.goodsAmount??i,
discountPercent:t?.discountPercent??t?.percent??t?.rate??t?.discountRate,discountBeforeTax:t?.discountBeforeTax??t?.beforeTax??t?.ckBeforeTax??t?.discountAmountBeforeTax,
discountAfterTax:t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax,promotionType:t?.promotionType||t?.type||t?.scope||t?.level||t?.discountType,
productCode:o,productName:s,lineType:n.isPromotionGift?"PROMO":t?.lineType||n.lineType||"SALE"}}function h(t){
return[f(t),t?.productCode||"",Number(t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax??0)||0,Number(t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??0)||0].join("|")
}function p(t){const n=s(t),e=[];for(const t of l(n.promotions))e.push(u(t));for(const n of l(t.promotions))e.push(u(n));for(const n of c(t))for(const t of m(n))e.push(u(t,n))
;const o=new Set;return e.filter(t=>{if(!f(t))return!1;const n=h(t);return!o.has(n)&&(o.add(n),!0)})}function g(t){const n=s(t)
;return Array.isArray(n.offsets)&&n.offsets.length?n.offsets:(t.displayRewards||[]).map(t=>({programCode:t.code,description:t.name,displayMonth:t.month,goodsAmount:t.goodsAmount,
quantityText:t.quantityText,offsetAmount:t.offsetAmount}))}function v(t){const n=s(t).summary||{};return{...t.totals||{},...n,totalVatAmount:n.totalVatAmount||t.totals?.tax||0,
amountInWords:n.amountInWords||t.totals?.totalAmountText||""}}function y(t){
const n=s(t).pagination||{},e=p(t),o=g(t),i=c(t),r=n.pagesPerCopy||(o.length||e.length>4||i.length>18?2:1);return{pagesPerCopy:r,copies:n.copies||["Liên 1","Liên 2"],
showPromotionHeaderOnFirstPage:r>1}}function b(t){const n=Number(String(t||0).replace(",","."))||0;return n?n.toLocaleString("vi-VN",{minimumFractionDigits:2,
maximumFractionDigits:2}):""}function f(t){return String(t?.promotionCode||t?.programCode||t?.ctkmCode||t?.code||"").trim()}function $(t){
const n=[t?.promotionType,t?.discountType,t?.level,t?.scope,t?.sourceType,t?.type,t?.promotionLevel,t?.applyScope,t?.mechanismType].filter(Boolean).join(" ").toLowerCase()
;return n.includes("group")||n.includes("invoice")||n.includes("order")||n.includes("bill")||n.includes("basket")||n.includes("cart")||n.includes("nhom")||n.includes("nhóm")||n.includes("hoa_don")||n.includes("hóa đơn")||n.includes("hoá đơn")||n.includes("don_hang")||n.includes("đơn hàng")
}function T(t){return String(t?.description||t?.promotionDescription||t?.programDescription||t?.promotionName||t?.name||t?.title||"").trim()}function A(t){
return Number(t?.qualifiedAmount??t?.basisAmount??t?.baseAmount??t?.purchaseAmountBeforeTax??t?.purchaseAmount??t?.goodsAmountBeforeTax??t?.goodsAmount??t?.amountBeforeTax??0)||0}
function N(t){return Number(t?.discountBeforeTax??t?.beforeTax??t?.ckBeforeTax??t?.discountAmountBeforeTax??t?.promotionBeforeTax??0)||0}function C(t){
return Number(t?.discountAfterTax??t?.afterTax??t?.ckAfterTax??t?.discountAmountAfterTax??t?.promotionAfterTax??0)||0}function w(t){const n=new Map;for(const e of t||[]){
const t=f(e);if(!t)continue;n.has(t)||n.set(t,{code:t,description:T(e),qualifiedAmount:0,discountPercent:"",discountBeforeTax:0,discountAfterTax:0,hasGroupDiscount:!1,
_sortIndex:n.size});const o=n.get(t);if(o.description||(o.description=T(e)),o.qualifiedAmount+=A(e),o.discountBeforeTax+=N(e),o.discountAfterTax+=C(e),$(e)){o.hasGroupDiscount=!0
;const t=b(e.discountPercent??e.percent??e.rate??e.discountRate);t&&!o.discountPercent&&(o.discountPercent=t)}}return Array.from(n.values()).sort((t,n)=>t._sortIndex-n._sortIndex)}
function P(t){return`(${String(t||"Liên 1").replace(/[()]/g,"").trim()})`}function x(t,n){return`${t}/ ${n}`}function I(t,n){return e(t,n||0)}function E(){
return'\n    <div class="dms-section-title">CHI TIẾT KHUYẾN MÃI: (B+C)</div>\n    <table class="dms-detail-table dms-promotion-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CTKM Tiền</th>\n          <th>Khuyến mãi bằng tiền</th>\n          <th style="width:25mm">Giá trị hàng hóa mua</th>\n          <th style="width:18mm">% chiết khấu</th>\n          <th style="width:24mm">Tiền CK trước thuế</th>\n          <th style="width:24mm">Tiền CK sau thuế</th>\n        </tr>\n      </thead>\n    </table>'
}function G(t){
return`\n    <table class="print-table">\n      <thead>\n        <tr>\n          <th style="width:8mm">STT</th>\n          <th style="width:24mm">Mã hàng</th>\n          <th>Tên hàng</th>\n          <th style="width:16mm">ĐVT</th>\n          <th style="width:18mm">Thùng/Lẻ</th>\n          <th style="width:18mm">SL lẻ</th>\n          <th style="width:24mm">Đơn giá</th>\n          <th style="width:28mm">Thành tiền</th>\n        </tr>\n      </thead>\n      <tbody>${t.items.length?t.items.map(n=>`\n      <tr>\n        <td class="center">${n.stt}</td>\n        <td class="mono">${o(n.code)}</td>\n        <td>${o(n.name)}</td>\n        <td class="center">${o(n.unit)}</td>\n        <td class="center">${o(n.caseDisplay)}</td>\n        <td class="right">${e(t,n.qty)}</td>\n        <td class="right">${e(t,n.price)}</td>\n        <td class="right">${e(t,n.amount)}</td>\n      </tr>`).join(""):'<tr><td colspan="8" class="center">Chưa có dòng hàng</td></tr>'}</tbody>\n    </table>`
}function R(t){const n=Array.isArray(t.masterKpis)?t.masterKpis:[];if(!n.length)return""
;const s=n.map(n=>`\n    <tr>\n      <td><b>${o(n.code)}</b>${n.note?`<div class="muted">Ghi chú: ${o(n.note)}</div>`:""}</td>\n      <td class="right">${e(t,n.productSaleAmount)}</td>\n      <td class="right">${e(t,n.promotionAmount)}</td>\n      <td class="right">${e(t,n.payableAmount)}</td>\n    </tr>`).join(""),i=t.masterKpiTotals||{}
;return`\n    <div class="section-title">BÁO CÁO KPI ĐƠN TỔNG ĐÃ GỘP</div>\n    <table class="print-table master-kpi-table">\n      <thead>\n        <tr>\n          <th>Mã đơn + ghi chú</th>\n          <th style="width:32mm">Giá trị đơn tổng</th>\n          <th style="width:32mm">Tổng khuyến mại</th>\n          <th style="width:36mm">Tổng tiền phải thu</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${s}\n        <tr class="invoice-total-row">\n          <td class="right">Tổng cộng</td>\n          <td class="right">${e(t,i.productSaleAmount)}</td>\n          <td class="right">${e(t,i.promotionAmount)}</td>\n          <td class="right">${e(t,i.payableAmount)}</td>\n        </tr>\n      </tbody>\n    </table>`
}function S(t,n,s=""){const i=s?` - ${s}`:""
;return`\n    <div class="simple-print-header">\n      <div>\n        <h2>${o(t.company.name)}</h2>\n        <p>${o(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?"Các đơn tổng":"Mã đơn tổng"}</b><span>${o(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">${o(n)}${o(i)}</h1>\n    <div class="info-grid">\n      <div><b>${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?"Gồm đơn tổng":"Mã đơn tổng"}:</b> ${o(t.document.masterOrderCodes&&t.document.masterOrderCodes.length?t.document.masterOrderCodes.join(", "):t.document.code)}</div>\n      <div><b>Ngày giao:</b> ${o(t.document.date)}</div>\n      <div><b>Nhân viên giao hàng:</b> ${o(t.delivery.code)} - ${o(t.delivery.name)}</div>\n      <div><b>Tuyến:</b> ${o(t.delivery.route)}</div>\n      ${"MASTER_AGGREGATE_SELECTED"===t.document.printMode?`<div><b>Số đơn tổng đã chọn:</b> ${e(t,t.document.selectedMasterOrderCount||0)}</div>`:""}\n      <div><b>Số đơn con:</b> ${e(t,t.totals.orderCount)}</div>\n      <div><b>Giá trị đơn tổng:</b> ${e(t,t.totals.totalAmount)} đ</div>\n      ${t.document.note?`<div class="full"><b>Ghi chú:</b> ${o(t.document.note)}</div>`:""}\n    </div>`
}function M(t){return(Number(t.qty||t.quantity||0)||0)*(Number(t.price||t.salePrice||0)||0)}function H(t,n,s=[],i={}){
const r=Boolean(i.isPromo),a=i.priceLabel||"Giá bán",d=i.amountLabel||"Thành tiền",c=s.length?s.map((n,s)=>{const i=M(n)
;return`\n        <tr class="${r?"promo-line-row":"sale-line-row"}">\n          <td class="center">${s+1}</td>\n          <td class="mono">${o(n.code)}</td>\n          <td>${o(n.name)}${r?'<div class="muted">Xuất khuyến mại</div>':""}</td>\n          <td class="center">${o(n.caseDisplay)}</td>\n          <td class="right">${e(t,n.qty)}</td>\n          <td class="right">${e(t,n.price)}</td>\n          <td class="right">${e(t,i)}</td>\n        </tr>`
}).join(""):`<tr><td colspan="7" class="center">${r?"Không có hàng khuyến mại":"Không có hàng bán"}</td></tr>`,l=s.reduce((t,n)=>t+Number(n.qty||0),0),m=s.reduce((t,n)=>t+M(n),0)
;return`\n    <div class="master-line-section ${r?"promo-section":"sale-section"}">\n      <div class="section-title">${o(n)}</div>\n      <table class="print-table master-picking-table">\n        <thead>\n          <tr>\n            <th style="width:4%">STT</th>\n            <th style="width:13%">Mã sản phẩm</th>\n            <th style="width:39%">Tên sản phẩm</th>\n            <th style="width:10%">Thùng/Lẻ</th>\n            <th style="width:8%">SL lẻ</th>\n            <th style="width:11%">${o(a)}</th>\n            <th style="width:15%">${o(d)}</th>\n          </tr>\n        </thead>\n        <tbody>\n          ${c}\n          <tr class="invoice-total-row">\n            <td colspan="4" class="right">Tổng ${o(n)}</td>\n            <td class="right">${e(t,l)}</td>\n            <td></td>\n            <td class="right">${e(t,m)}</td>\n          </tr>\n        </tbody>\n      </table>\n    </div>`
}function O(t){return(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],saleItems:t.items||[],
promoItems:[],totalQty:t.totals.totalQty,totalAmount:t.totals.totalAmount}]).map(n=>{
const e=Array.isArray(n.saleItems)?n.saleItems:(n.items||[]).filter(t=>!t.isPromo&&"PROMO"!==t.lineType),s=Array.isArray(n.promoItems)?n.promoItems:(n.items||[]).filter(t=>t.isPromo||"PROMO"===t.lineType)
;return`\n      <div class="master-warehouse-block">\n        <div class="section-title master-warehouse-title">${o(n.name||n.code)}</div>\n        ${H(t,`${n.name||n.code} - Hàng bán`,e)}\n        ${H(t,`${n.name||n.code} - Xuất khuyến mại`,s,{
isPromo:!0})}\n      </div>`}).join("")}function k(t=["Người lập phiếu","Khách hàng","Thủ kho / Giao hàng"]){
return`\n    <div class="signature-row">\n      ${t.map(t=>`<div><b>${o(t)}</b><span>(Ký, ghi rõ họ tên)</span></div>`).join("")}\n    </div>`}function K(){
return"\n  <div class=\"print-preview-actions\">\n    <button type=\"button\" onclick=\"window.close()\">Bỏ qua</button>\n    <button type=\"button\" onclick=\"window.print()\">In đơn</button>\n    <button type=\"button\" onclick=\"exportCurrentPrintToExcel()\">Xuất Excel</button>\n  </div>\n  <script>\n    function exportCurrentPrintToExcel(){\n      var pages = Array.prototype.slice.call(document.querySelectorAll('.print-page, .dms-print-page'));\n      var html = pages.length ? pages.map(function(page){ return page.outerHTML; }).join('') : document.body.innerHTML;\n      var fullHtml = '<!doctype html><html><head><meta charset=\"utf-8\"><style>table{border-collapse:collapse}td,th{border:1px solid #999;padding:4px}</style></head><body>' + html + '</body></html>';\n      var blob = new Blob(['\ufeff' + fullHtml], { type: 'application/vnd.ms-excel;charset=utf-8;' });\n      var a = document.createElement('a');\n      a.href = URL.createObjectURL(blob);\n      var title = (document.title || 'ban-in').replace(/[^a-zA-Z0-9_-]+/g, '-').replace(/^-+|-+$/g, '') || 'ban-in';\n      a.download = title + '.xls';\n      document.body.appendChild(a);\n      a.click();\n      a.remove();\n      setTimeout(function(){ URL.revokeObjectURL(a.href); }, 1000);\n    }\n  <\/script>"
}function B(t,n,e,s={}){const i=s.compact?" compact-print":""
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${o(t)} - ${o(n.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body>\n  ${K()}\n  <div class="print-page${i}">\n    ${e}\n    <div class="print-footer">In lúc: ${o(n.meta.printedAt)}</div>\n  </div>\n</body>\n</html>`
}function D(t){const n="MASTER_AGGREGATE_SELECTED"===t.document.printMode,s=n?"ĐƠN TỔNG GỘP":"PHIẾU NHẶT HÀNG ĐƠN TỔNG";if(n){
const n=(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],saleItems:t.items||[],promoItems:[]
}]).map(n=>{const i={qty:(n.items||[]).reduce((t,n)=>t+Number(n.qty||n.quantity||0),0),amount:(n.items||[]).reduce((t,n)=>t+Number(n.amount||0),0)}
;return`\n        <div class="print-page">\n          ${S(t,s,n.name||n.code)}\n          ${R(t)}\n          <div class="master-warehouse-block">\n            <div class="section-title master-warehouse-title">${o(n.name||n.code)}</div>\n            ${H(t,`${n.name||n.code} - Hàng bán`,Array.isArray(n.saleItems)?n.saleItems:[])}\n            ${H(t,`${n.name||n.code} - Xuất khuyến mại`,Array.isArray(n.promoItems)?n.promoItems:[],{
isPromo:!0
})}\n          </div>\n          <div class="total-box">\n            <div><span>Tổng số lượng liên ${o(n.name||n.code)}:</span><b>${e(t,i.qty)}</b></div>\n            <div><span>Giá trị liên ${o(n.name||n.code)}:</span><b>${e(t,i.amount)}</b></div>\n            <div><span>Số đơn con:</span><b>${e(t,t.totals.orderCount)}</b></div>\n          </div>\n          ${k(["Người lập phiếu","Người giao hàng",n.name||n.code])}\n          <div class="print-footer">In lúc: ${o(t.meta.printedAt)}</div>\n        </div>`
}).join("")
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${o(s)} - ${o(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body>\n  ${K()}\n  ${n}\n</body>\n</html>`
}
const i=`\n    ${S(t,s)}\n    ${R(t)}\n    ${O(t)}\n    <div class="total-box">\n      <div><span>Tổng số lượng:</span><b>${e(t,t.totals.totalQty)}</b></div>\n      <div><span>Giá trị đơn tổng:</span><b>${e(t,t.totals.totalAmount)}</b></div>\n      <div><span>Số đơn con:</span><b>${e(t,t.totals.orderCount)}</b></div>\n    </div>\n    ${k(["Người lập phiếu","Người giao hàng","Kho HC","Kho PC"])}`
;return B(s,t,i)}function L(t){const n=String(t.document?.printMode||"").toUpperCase();return n.includes("RETURN")?"RETURN":n.includes("IMPORT")?"IMPORT":"MASTER"}function q(t){
if(t.document?.title)return t.document.title;const n=L(t)
;return"RETURN"===n?"ĐƠN TỔNG TRẢ HÀNG":"IMPORT"===n?"IMPORT_AGGREGATE_SELECTED"===t.document?.printMode?"ĐƠN TỔNG NHẬP KHO":"PHIẾU NHẬP KHO":"MASTER_AGGREGATE_SELECTED"===t.document?.printMode?"ĐƠN TỔNG GỘP":"PHIẾU NHẶT HÀNG ĐƠN TỔNG"
}function _(t,n){
const s=Array.isArray(t.document?.sourceCodes)&&t.document.sourceCodes.length?t.document.sourceCodes:Array.isArray(t.document?.masterOrderCodes)?t.document.masterOrderCodes:[],i="RETURN"===n?"Phiếu trả hàng":"IMPORT"===n?"Phiếu nhập":"Đơn tổng"
;return`\n    <div class="info-grid print-info-compact">\n      <div><b>Ngày chứng từ:</b> ${o(t.document.date)}</div>\n      ${"IMPORT"===n?`<div><b>Nhà cung cấp:</b> ${o(t.customer.name)}</div>`:""}\n      ${"IMPORT"!==n?`<div><b>NV giao hàng:</b> ${o(t.delivery.code)}${t.delivery.name?` - ${o(t.delivery.name)}`:""}</div>`:""}\n      ${t.delivery.route?`<div><b>Tuyến:</b> ${o(t.delivery.route)}</div>`:""}\n      <div><b>Số chứng từ con:</b> ${e(t,t.totals.orderCount)}</div>\n      ${s.length?`<div class="full"><b>${i}:</b> ${o(s.join(", "))}</div>`:""}\n      ${t.document.note?`<div class="full"><b>Ghi chú:</b> ${o(t.document.note)}</div>`:""}\n    </div>`
}function U(t){const n=L(t),s=q(t),i=(Array.isArray(t.warehouseGroups)&&t.warehouseGroups.length?t.warehouseGroups:[{code:"KHO_HC",name:"KHO HC",items:t.items||[],
saleItems:t.items||[],promoItems:[],importItems:[],returnItems:[]}]).map((i,r)=>{
const a=Array.isArray(i.saleItems)?i.saleItems:[],d=Array.isArray(i.promoItems)?i.promoItems:[],c=Array.isArray(i.importItems)&&i.importItems.length?i.importItems:"IMPORT"===n&&i.items||[],l=Array.isArray(i.returnItems)&&i.returnItems.length?i.returnItems:"RETURN"===n&&i.items||[],m="IMPORT"===n?c:"RETURN"===n?l:[...a,...d],u=m.reduce((t,n)=>t+Number(n.qty||n.quantity||0),0),h=m.reduce((t,n)=>t+M(n),0),p="IMPORT"===n?["Người lập phiếu","Người giao hàng","Thủ kho"]:"RETURN"===n?["Người lập phiếu","Nhân viên giao hàng","Thủ kho"]:["Người lập phiếu","Người giao hàng",i.name||i.code],g="IMPORT"===n?H(t,`${i.name||i.code} - Hàng nhập kho`,c,{
priceLabel:"Giá nhập"}):"RETURN"===n?H(t,`${i.name||i.code} - Hàng trả nhập kho`,l,{priceLabel:"Giá trả"}):`${H(t,`${i.name||i.code} - Hàng bán`,a,{priceLabel:"Giá bán"
})}${H(t,`${i.name||i.code} - Xuất khuyến mại`,d,{isPromo:!0,priceLabel:"Giá tham chiếu"})}`
;return`\n      <section class="print-page warehouse-picking-page${r>0?" page-break-before":""}">\n        <div class="simple-print-header">\n          <div><h2>${o(t.company.name)}</h2><p>${o(t.company.address)}</p></div>\n          <div class="print-code"><b>Mã chứng từ</b><span>${o(t.document.code)}</span></div>\n        </div>\n        <h1 class="print-title">${o(s)} - ${o(i.name||i.code)}</h1>\n        ${_(t,n)}\n        ${0===r?R(t):""}\n        ${g}\n        <div class="total-box print-total-compact">\n          <div><span>Tổng số lượng:</span><b>${e(t,u)}</b></div>\n          <div><span>Tổng giá trị:</span><b>${e(t,h)}</b></div>\n          <div><span>Số chứng từ con:</span><b>${e(t,t.totals.orderCount)}</b></div>\n        </div>\n        ${k(p)}\n        <div class="print-footer">In lúc: ${o(t.meta.printedAt)}</div>\n      </section>`
}).join("")
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>${o(s)} - ${o(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body class="warehouse-picking-body">\n  ${K()}\n  ${i}\n</body>\n</html>`
}function V(t){
return B("PHIẾU NHẬP KHO",t,`\n    <div class="simple-print-header">\n      <div>\n        <h2>${o(t.company.name)}</h2>\n        <p>${o(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>Mã phiếu</b><span>${o(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">PHIẾU NHẬP KHO</h1>\n    <div class="info-grid">\n      <div><b>Ngày nhập:</b> ${o(t.document.date)}</div>\n      <div><b>Nhà cung cấp:</b> ${o(t.customer.name)}</div>\n      <div class="full"><b>Ghi chú:</b> ${o(t.document.note)}</div>\n    </div>\n    ${G(t)}\n    <div class="total-box">\n      <div><span>Tổng số lượng nhập:</span><b>${e(t,t.totals.totalQty)}</b></div>\n      <div><span>Tổng giá trị:</span><b>${e(t,t.totals.totalAmount)}</b></div>\n    </div>\n    ${k(["Người lập phiếu","Người giao hàng","Thủ kho"])}`)
}function j(t){
return B("PHIẾU THU TIỀN",t,`\n    <div class="simple-print-header">\n      <div>\n        <h2>${o(t.company.name)}</h2>\n        <p>${o(t.company.address)}</p>\n      </div>\n      <div class="print-code"><b>Mã phiếu</b><span>${o(t.document.code)}</span></div>\n    </div>\n    <h1 class="print-title">PHIẾU THU TIỀN</h1>\n    <div class="info-grid">\n      <div><b>Ngày thu:</b> ${o(t.document.date)}</div>\n      <div><b>Người thu:</b> ${o(t.staff.name)}</div>\n      <div><b>Mã KH:</b> ${o(t.customer.code)}</div>\n      <div><b>Khách hàng:</b> ${o(t.customer.name)}</div>\n      <div class="full"><b>Địa chỉ:</b> ${o(t.customer.address)}</div>\n    </div>\n    <div class="receipt-money"><span>Số tiền thu:</span><b>${e(t,t.totals.paid||t.totals.totalAmount)} đ</b></div>\n    <p class="note"><b>Nội dung:</b> ${o(t.document.note||"Thu tiền bán hàng")}</p>\n    ${k(["Người lập phiếu","Người nộp tiền","Thủ quỹ"])}`)
}function F(t,n=null,s={}){const i=Array.isArray(n)?n:c(t),r=v(t),a=!1!==s.showTotal
;return`\n    <table class="dms-invoice-table">\n      <thead>\n        <tr>\n          <th style="width:4%">STT</th>\n          <th style="width:9%">Mã hàng</th>\n          <th style="width:31%">Tên sản phẩm</th>\n          <th style="width:7%">Số lượng<br/>(CS/SU)</th>\n          <th style="width:6%">Số<br/>lượng<br/>(lẻ)</th>\n          <th style="width:9%">Đơn Giá<br/>(Trước Thuế/KM)</th>\n          <th style="width:9%">Đơn Giá (Sau<br/>Thuế, Trước KM)</th>\n          <th style="width:9%">Đơn giá<br/>(Sau Thuế/<br/>KM&CK)</th>\n          <th style="width:7%">Thuế<br/>GTGT</th>\n          <th style="width:9%">Thành tiền<br/>(Sau Thuế/<br/>KM&CK)</th>\n        </tr>\n        <tr class="dms-formula-row">\n          <th>A</th><th></th><th></th><th>1</th><th>2</th><th>3</th><th>4</th><th>5</th><th>6</th><th>7=(5*2)</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${i.length?i.map(n=>`\n      <tr>\n        <td class="center">${o(n.lineNo)}</td>\n        <td class="mono">${o(n.productCode)}</td>\n        <td class="dms-product-name">${o(n.productName)}</td>\n        <td class="center">${o(n.quantityCsSu)}</td>\n        <td class="right">${e(t,n.quantity)}</td>\n        <td class="right">${e(t,n.priceBeforeTaxBeforePromotion)}</td>\n        <td class="right">${e(t,n.priceAfterTaxBeforePromotion)}</td>\n        <td class="right">${e(t,n.priceAfterTaxAfterPromotion)}</td>\n        <td class="right">${e(t,n.vatAmount)}</td>\n        <td class="right">${e(t,n.lineAmount)}</td>\n      </tr>`).join(""):'<tr><td colspan="10" class="center">Chưa có dòng hàng</td></tr>'}\n        ${a?`<tr class="dms-total-row">\n          <td colspan="4" class="center">Tổng cộng (A)</td>\n          <td class="right">${I(t,r.totalQty)}</td>\n          <td></td><td></td><td></td>\n          <td></td>\n          <td class="right">${I(t,r.goodsAmountAfterPromotion)}</td>\n        </tr>`:""}\n      </tbody>\n    </table>`
}function Y(t){
const n=w(p(t)),e=v(t),s=n.length?n.map(n=>`\n      <tr>\n        <td class="mono">${o(n.code)}</td>\n        <td>${o(n.description)}</td>\n        <td class="right">${I(t,n.qualifiedAmount)}</td>\n        <td class="right">${n.hasGroupDiscount?o(n.discountPercent):""}</td>\n        <td class="right">${I(t,n.discountBeforeTax)}</td>\n        <td class="right">${I(t,n.discountAfterTax)}</td>\n      </tr>`).join(""):'<tr class="dms-empty-row"><td colspan="6">&nbsp;</td></tr>',i=n.length?n.reduce((t,n)=>t+Number(n.discountAfterTax||0),0):Number(e.totalPromotionAmount??e.promotionAmount??t.totals?.promotionValue??0)||0
;return`\n    <div class="dms-section-title">CHI TIẾT KHUYẾN MÃI: (B+C)</div>\n    <table class="dms-detail-table dms-promotion-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CTKM Tiền</th>\n          <th>Khuyến mãi bằng tiền</th>\n          <th style="width:25mm">Giá trị hàng hóa mua</th>\n          <th style="width:18mm">% chiết khấu</th>\n          <th style="width:24mm">Tiền CK trước thuế</th>\n          <th style="width:24mm">Tiền CK sau thuế</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${s}\n        <tr class="dms-total-row"><td colspan="5" class="right">Tổng giá trị khuyến mãi tiền (C)</td><td class="right">${I(t,i)}</td></tr>\n      </tbody>\n    </table>`
}function X(t){const n=g(t),e=v(t),s=Number(e.totalOffsetAmount??e.displayRewardOffset??t.totals?.displayRewardTotal??0)||0
;return n.length||s?`\n    <div class="dms-section-title">CHI TIẾT CẤN TRỪ NỢ:(D+E)</div>\n    <table class="dms-detail-table dms-reward-table">\n      <thead>\n        <tr>\n          <th style="width:28mm">Mã CT Trưng bày</th>\n          <th>Nội dung Chương trình trưng bày</th>\n          <th style="width:20mm">Tháng trưng bày</th>\n          <th style="width:24mm">Chi trả trưng bày (hàng hóa)</th>\n          <th style="width:20mm">Số lượng (Thùng/lẻ)</th>\n          <th style="width:25mm">Chi trả trưng bày (cấn trừ nợ)</th>\n        </tr>\n      </thead>\n      <tbody>\n        ${n.length?n.map(n=>`\n      <tr>\n        <td class="mono">${o(n.programCode)}</td>\n        <td>${o(n.description)}</td>\n        <td class="center">${o(n.displayMonth||n.month)}</td>\n        <td class="right">${n.goodsAmount?I(t,n.goodsAmount):""}</td>\n        <td class="center">${o(n.quantityText)}</td>\n        <td class="right">${I(t,n.offsetAmount)}</td>\n      </tr>`).join(""):'<tr class="dms-empty-row"><td colspan="6">&nbsp;</td></tr>'}\n        <tr class="dms-total-row"><td colspan="5" class="right">Tổng giá trị nhận được từ CT trưng bày (D)</td><td class="right">${I(t,s)}</td></tr>\n      </tbody>\n    </table>`:""
}function Q(t,n,e,s){
const c=i(t),l=r(t),m=a(t),u=d(t),h=P(n),p=x(e,s),g=`${o(u.staffCode)}${u.staffName?` - ${o(u.staffName)}`:""}${u.phone?` - ${o(u.phone)}`:""}`,v=`${o(m.customerCode)}${m.customerName?` - ${o(m.customerName)}`:""}${m.phone?` - ${o(m.phone)}`:""}`,y=`${o(l.code)}${l.name?` - ${o(l.name)}`:""}`
;return`\n    <div class="dms-header-lines dms-invoice-header-left dms-invoice-header-right">\n      <div class="dms-title-header">\n        <div></div>\n        <div class="dms-title-line">PHIẾU GIAO NHẬN VÀ THANH TOÁN</div>\n        <div class="dms-truck-cell"><span>Số xe tải:</span> ${o(c.truckNo)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Số hóa đơn:</span> ${o(c.invoiceCode)}</div>\n        <div class="dms-line-right dms-line-right-split">\n          <span><span>Loại hóa đơn:</span> ${o(c.invoiceType)}</span>\n          <span class="dms-copy-page-cell"><span>${o(h)}</span><span>Trang: ${p}</span></span>\n        </div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Số đơn hàng:</span> ${o(c.orderCode)}</div>\n        <div class="dms-line-right"><span>Thời gian đặt hàng:</span> ${o(c.orderDateTime)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>NVBH:</span> ${g}</div>\n        <div class="dms-line-right"><span>Nhà phân phối:</span> ${y}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Khách hàng - Điện thoại:</span> ${v}</div>\n        <div class="dms-line-right"><span>Địa chỉ:</span> ${o(l.address)}</div>\n      </div>\n\n      <div class="dms-header-line">\n        <div class="dms-line-left"><span>Địa chỉ giao hàng:</span> ${o(m.deliveryAddress)}</div>\n        <div class="dms-line-right"><span>Điện thoại:</span> ${o(l.phone)}</div>\n      </div>\n\n      <div class="dms-header-line dms-single-line">\n        <div class="dms-line-left"><span>Điều khoản thanh toán:</span> ${o(c.paymentTerm)}</div>\n      </div>\n\n      <div class="dms-header-line dms-single-line">\n        <div class="dms-line-left"><span>MST:</span> ${o(c.taxCode||m.taxCode)}</div>\n      </div>\n    </div>`
}function W(t=[],n=24){const e=Math.max(1,Number(n||24)),o=[];for(let n=0;n<t.length;n+=e)o.push(t.slice(n,n+e));return o.length?o:[[]]}function z(t){
return p(t).length>0||g(t).length>0}function Z(t){const n=y(t),e=v(t)
;return`<!DOCTYPE html>\n<html lang="vi">\n<head>\n  <meta charset="UTF-8" />\n  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n  <title>Phiếu giao nhận DMS - ${o(t.document.code)}</title>\n  <link rel="stylesheet" href="/print.css" />\n  <link rel="stylesheet" href="/print-tokens.css?v=print-domain-v1" />\n</head>\n<body class="dms-print-body">\n  ${K()}\n  ${n.copies.map(s=>{
const i=c(t),r=W(i,Number(n.itemPageSize||24)),a=z(t)&&(i.length>18||n.detailRows>4||n.pagesPerCopy>r.length),d=r.length+(a?1:0);return r.map((n,i)=>{const c=i===r.length-1
;return`\n        <section class="print-page dms-print-page">\n          ${Q(t,s,i+1,d)}\n          ${F(t,n,{showTotal:c
})}\n          ${c?`\n      <table class="dms-summary-split-table">\n        <tbody>\n          <tr class="dms-payable-row">\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Số tiền phải thanh toán (A7-D-E-H)</td>\n            <td class="dms-summary-value-cell">${I(t,e.payableAmount??t.totals?.payable??t.totals?.totalAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tổng tiền sau thuế chưa trừ KM (G) = (2)*(4):</td>\n            <td class="dms-summary-value-cell">${I(t,e.grossAmountBeforePromotion??t.totals?.goodsAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell dms-amount-words-cell"><b>Số tiền viết bằng chữ :</b> <span class="dms-amount-words-text">${o(e.amountInWords||t.totals.totalAmountText)}</span></td>\n            <td class="dms-summary-label-cell">Tổng trị giá khuyến mãi bằng hàng và tiền (B+C):</td>\n            <td class="dms-summary-value-cell">${I(t,e.totalPromotionAmount??t.totals?.promotionValue)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Cấn trừ tiền (D+E+H):</td>\n            <td class="dms-summary-value-cell">${I(t,e.totalOffsetAmount??t.totals?.displayRewardTotal)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tổng tiền CK của NPP (F)=(G-C)* 0,00% :</td>\n            <td class="dms-summary-value-cell">${I(t,e.nppDiscountAmount)}</td>\n          </tr>\n          <tr>\n            <td class="dms-summary-left-cell"></td>\n            <td class="dms-summary-label-cell">Tỉ lệ KM & CK của đơn hàng [(B+C+F)/G]*100%:</td>\n            <td class="dms-summary-value-cell">${b(e.promotionRate??t.totals?.promotionRate)}%</td>\n          </tr>\n        </tbody>\n      </table>\n      <div class="dms-signature">\n        <div><b>Người lập biểu</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Người bán hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Nhân viên giao hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n        <div><b>Người nhận hàng</b><span>(Ký, ghi rõ họ tên)</span></div>\n      </div>`:""}\n          ${c&&!a?Y(t)+X(t):""}\n          ${c&&a?E():""}\n        </section>`
}).join("")+(a?`\n      <section class="print-page dms-print-page">\n        ${Q(t,s,r.length+1,d)}\n        ${Y(t)}\n        ${X(t)}\n      </section>`:"")
}).join("")}\n</body>\n</html>`}module.exports={ORDER_SINGLE:t,DMS_DELIVERY_INVOICE:t,SALES_INVOICE:t,SALES_INVOICE_DMS_EXACT_V1:t,ORDER_TOTAL:U,WAREHOUSE_PICKING:U,IMPORT_ORDER:U,
PAYMENT_RECEIPT:j};
