'use strict';

const flexModel = require('./_flexModel');

module.exports = flexModel('ArAdjustment', 'arAdjustments', {
  id: String,
  tenantId: String,
  adjustmentCode: String,
  correctionId: String,
  correctionCode: String,
  customerCode: String,
  customerId: String,
  customerName: String,
  beforeDebt: Number,
  adjustAmount: Number,
  afterDebt: Number,
  reason: String,
  reasonCode: String,
  reasonText: String,
  direction: String,
  idempotencyKey: String,
  sourceType: String,
  sourceId: String,
  sourceCode: String,
  arLedgerId: String,
  arLedgerCode: String,
  adjustmentKind: String,
  isRollback: Boolean,
  rollbackOf: String,
  originalAdjustmentId: String,
  originalLedgerId: String,
  rollbackLedgerId: String,
  rollbackLedgerCode: String,
  createdBy: Object,
  approvedBy: Object,
  status: String,
  createdAt: String,
  approvedAt: String,
  appliedAt: String,
  rolledBackAt: String,
  auditTrail: Array,
  metadata: Object
});
