const flexModel = require('./_flexModel');

module.exports = flexModel('ArDocument', 'arDocuments', {
  id: String,
  code: String,
  sourceType: String,
  sourceOrderId: String,
  sourceOrderCode: String,
  orderId: String,
  orderCode: String,
  salesOrderId: String,
  salesOrderCode: String,
  customerId: String,
  customerCode: String,
  customerName: String,
  salesmanCode: String,
  salesmanName: String,
  salesStaffCode: String,
  salesStaffName: String,
  deliveryStaffCode: String,
  deliveryStaffName: String,
  documentDate: String,
  deliveryDate: String,
  totalReceivable: Number,
  totalPaid: Number,
  cashAmount: Number,
  bankAmount: Number,
  returnAmount: Number,
  bonusAmount: Number,
  totalCredit: Number,
  remainingDebt: Number,
  status: String,
  accountingStatus: String,
  locked: Boolean,
  version: Number,
  lines: Array,
  source: String,
  confirmedAt: String,
  confirmedBy: String,
  reopenedAt: String,
  reopenedBy: String,
  reopenReason: String,
  createdAt: String,
  updatedAt: String
});
