const flexModel = require('./_flexModel');

module.exports = flexModel('DeliveryCashSubmission', 'deliveryCashSubmissions', {
  id: String,
  code: String,
  deliveryDate: String,
  deliveryStaffCode: String,
  deliveryStaffName: String,
  reportCashAmount: Number,
  reportBankAmount: Number,
  reportCurrentOrderCashAmount: Number,
  reportCurrentOrderBankAmount: Number,
  reportOldDebtCashAmount: Number,
  reportOldDebtBankAmount: Number,
  submittedCashAmount: Number,
  submittedBankAmount: Number,
  totalActualCashAmount: Number,
  totalActualBankAmount: Number,
  remainingCashAmount: Number,
  remainingBankAmount: Number,
  remittanceDateFrom: String,
  remittanceDateTo: String,
  remittanceDateMultiple: Boolean,
  remittanceLines: [{
    lineId: String,
    method: String,
    fundType: String,
    invalidMethod: Boolean,
    amount: Number,
    remittanceDate: String,
    bankAccountCode: String,
    bankReference: String,
    status: String,
    confirmedAt: String,
    confirmedBy: String,
    fundLedgerId: String,
    idempotencyKey: String,
    reversedAt: String,
    reversedBy: String,
    reversalFundLedgerId: String,
    legacyDerived: Boolean,
    manualReviewRequired: Boolean,
    note: String
  }],
  differenceCashAmount: Number,
  differenceBankAmount: Number,
  orderCodes: [String],
  orderIds: [String],
  status: String, // pending | confirmed | cancelled
  matchStatus: String, // matched | mismatch
  fundPosted: Boolean,
  hasPostedLines: Boolean,
  manualReviewRequired: Boolean,
  postedAt: String,
  confirmedAt: String,
  confirmedBy: String,
  shortageClassifiedAt: String,
  shortageClassifiedBy: String,
  note: String,
  createdBy: String,
  createdAt: String,
  updatedAt: String
});
