'use strict';

const flexModel = require('./_flexModel');

module.exports = flexModel('DeliveryCloseoutCorrection', 'deliveryCloseoutCorrections', {
  id: String,
  code: String,
  correctionCode: String,
  tenantId: String,

  originalCloseoutId: String,
  originalCloseoutCode: String,
  newCloseoutId: String,
  newCloseoutCode: String,
  originalCloseoutVersion: Number,
  newCloseoutVersion: Number,

  deliveryDate: String,
  deliveryStaffCode: String,
  deliveryStaffName: String,
  salesStaffCode: String,
  salesStaffName: String,

  customerId: String,
  customerCode: String,
  customerName: String,
  salesOrderId: String,
  salesOrderCode: String,
  orderId: String,
  orderCode: String,

  previousReturnAmount: Number,
  previousCashAmount: Number,
  previousBankAmount: Number,
  previousRewardAmount: Number,
  previousCashCollectedAmount: Number,
  previousCollectedAmount: Number,
  previousDebtAmount: Number,
  newReturnAmount: Number,
  newCashAmount: Number,
  newBankAmount: Number,
  newRewardAmount: Number,
  newCashCollectedAmount: Number,
  newCollectedAmount: Number,
  newDebtAmount: Number,
  cashAmount: Number,
  bankAmount: Number,
  rewardAmount: Number,
  returnAmount: Number,
  debtAmount: Number,
  finalDebtAmount: Number,

  returnAdjustmentAmount: Number,
  cashDeltaAmount: Number,
  bankDeltaAmount: Number,
  rewardDeltaAmount: Number,
  totalCollectedDelta: Number,
  cashAdjustmentAmount: Number,
  debtDeltaAmount: Number,
  debtAdjustmentAmount: Number,
  returnAdjustmentItems: Array,
  cashAdjustmentLines: Array,

  reason: String,
  note: String,
  status: String,
  sourceType: String,
  idempotencyKey: String,
  arDebtAdjustmentLedgerId: String,
  arDebtAdjustmentLedgerCode: String,

  createdBy: String,
  createdAt: String,
  updatedAt: String,
  auditTrail: Array,
  metadata: Object
});
