const flexModel = require('./_flexModel');
module.exports = flexModel('ReturnOrder', 'returnOrders', {
  id: String,
  code: String,
  customerId: String,
  customerName: String,
  sourceOrderId: String,
  salesOrderId: String,
  salesOrderCode: String,
  orderId: String,
  orderCode: String,
  masterOrderId: String,
  masterOrderCode: String,
  items: Array,
  amount: Number,
  returnAmount: Number,
  status: String,
  returnStatus: String,
  accountingStatus: String,
  accountingConfirmed: Boolean,
  accountingConfirmedAt: String,
  accountingBatchId: String,
  arPosted: Boolean,
  arPostedAt: String,
  createdAt: String
});
